spring:
  application:
    name: flv-exporter

# Prometheus metrics endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      # 禁用所有默认指标
      jvm: false
      system: false
      process: false
      http: false
      tomcat: false
      logback: false
      hikaricp: false
      jdbc: false
    export:
      prometheus:
        enabled: true

# FLV检测配置
flv:
  check:
    interval: 30000  # 检测间隔(毫秒)，默认30秒
    timeout: 10000   # 连接超时(毫秒)，默认10秒
    threads: 20      # 并发检测线程数，默认10个
    retries: 3       # 失败重试次数，默认3次
  urls:
    # 请根据实际需要配置FLV流URL
    demo:
      - https://example.com/stream1.flv
      - https://example.com/stream2.flv
    test:
      - https://example.com/stream3.flv
      - https://example.com/stream4.flv